// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get('apiKey'),
    appId: dotenv.get('appId'),
    messagingSenderId: dotenv.get('messagingSenderId'),
    projectId: dotenv.get('projectId'),
    authDomain: dotenv.get('authDomain'),
    databaseURL: dotenv.get('databaseURL'),
    storageBucket: dotenv.get('storageBucket'),
    measurementId: dotenv.get('measurementId'),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get('apiKeyAndroid'),
    appId: dotenv.get('appId'),
    messagingSenderId: dotenv.get('messagingSenderId'),
    projectId: dotenv.get('projectId'),
    databaseURL: dotenv.get('databaseURL'),
    storageBucket: dotenv.get('storageBucket'),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get('apiKeyIos'),
    appId: dotenv.get('appId'),
    messagingSenderId: dotenv.get('messagingSenderId'),
    projectId: dotenv.get('projectId'),
    databaseURL: dotenv.get('databaseURL'),
    storageBucket: dotenv.get('storageBucket'),
    iosClientId: dotenv.get('iosClientId'),
    iosBundleId: dotenv.get('iosBundleId'),
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.get('apiKeyIos'),
    appId: dotenv.get('appId'),
    messagingSenderId: dotenv.get('messagingSenderId'),
    projectId: dotenv.get('projectId'),
    databaseURL: dotenv.get('databaseURL'),
    storageBucket: dotenv.get('storageBucket'),
    iosClientId: dotenv.get('iosClientId'),
    iosBundleId: dotenv.get('iosBundleId'),
  );
}
